const MAX_ANSWER_CHARS = 12_000;
const MAX_SOURCE_TITLE_CHARS = 240;
const MAX_SOURCE_PUBLISHED_AT_CHARS = 80;
const MAX_RESULT_CONTENT_CHARS = 3_000;

function boundedText(value, maxChars) {
  if (typeof value !== "string") return "";
  return value.trim().slice(0, maxChars);
}

function normalizeSource(result) {
  if (!result || typeof result !== "object") return null;
  const rawUrl = boundedText(result.url, 2_048);
  if (!rawUrl) return null;

  let url;
  try {
    url = new URL(rawUrl);
  } catch {
    return null;
  }
  if (url.protocol !== "https:" && url.protocol !== "http:") return null;

  const title =
    boundedText(result.title, MAX_SOURCE_TITLE_CHARS) || url.hostname;
  const publishedAt = boundedText(
    result.published_date || result.publishedAt,
    MAX_SOURCE_PUBLISHED_AT_CHARS,
  );
  return publishedAt ? { title, url: url.toString(), publishedAt } : { title, url: url.toString() };
}

function buildAnswer(data) {
  const directAnswer = boundedText(data?.answer, MAX_ANSWER_CHARS);
  if (directAnswer) return directAnswer;

  if (!Array.isArray(data?.results)) return "";
  return data.results
    .map((result) => boundedText(result?.content, MAX_RESULT_CONTENT_CHARS))
    .filter(Boolean)
    .join("\n\n")
    .slice(0, MAX_ANSWER_CHARS);
}

class TavilySearch {
  /**
   * TASK-020 Phase 1-D: `lang` is a new, optional second parameter
   * ("bn" | "en" | undefined). When provided, a short fixed instruction
   * is appended to the outgoing query text asking Tavily's own
   * answer-generation to reply in that language.
   *
   * BEST-EFFORT, NOT GUARANTEED: Tavily's `include_answer` summary is
   * generated by Tavily's own model from its own search results: this
   * appended instruction is a hint, not an enforced contract on Tavily's
   * side, and this file has no way to verify or correct the language of
   * what comes back. No second LLM call is added here to translate or
   * re-summarize Tavily's answer, and no new AI provider is introduced.
   *
   * Backward compatible: omitting `lang` (or passing a value other than
   * "bn"/"en") sends exactly the same request as before this change.
   */
  async search(query, lang) {
    const apiKey = process.env.TAVILY_API_KEY;
    if (!apiKey) {
      return null;
    }

    let outgoingQuery = query;
    if (lang === "bn") {
      outgoingQuery = `${query} (দয়া করে বাংলায় উত্তর দিন)`;
    } else if (lang === "en") {
      outgoingQuery = `${query} (please answer in English)`;
    }

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 15_000);
    try {
      const response = await fetch("https://api.tavily.com/search", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          api_key: apiKey,
          query: outgoingQuery,
          search_depth: "basic",
          include_answer: true, // Tavily নিজে থেকেই একটি AI সামারি পাঠাবে
          max_results: 3,
        }),
        signal: controller.signal,
      });

      if (!response.ok) return null;

      const data = await response.json();
      const answer = buildAnswer(data);
      const sources = Array.isArray(data?.results)
        ? data.results.map(normalizeSource).filter(Boolean).slice(0, 3)
        : [];

      // A live/current answer without a source link is not evidence-backed.
      // Do not present it as verified web research to the customer.
      if (!answer || sources.length === 0) return null;

      return {
        answer,
        sources,
        retrievedAt: new Date().toISOString(),
      };
    } catch {
      console.error("[TAVILY] Request failed");
      return null;
    } finally {
      clearTimeout(timeout);
    }
  }
}

module.exports = new TavilySearch();
