class TavilySearch {
  /**
   * TASK-020 Phase 1-D: `lang` is a new, optional second parameter
   * ("bn" | "en" | undefined). When provided, a short fixed instruction
   * is appended to the outgoing query text asking Tavily's own
   * answer-generation to reply in that language.
   *
   * BEST-EFFORT, NOT GUARANTEED: Tavily's `include_answer` summary is
   * generated by Tavily's own model from its own search results: this
   * appended instruction is a hint, not an enforced contract on Tavily's
   * side, and this file has no way to verify or correct the language of
   * what comes back. No second LLM call is added here to translate or
   * re-summarize Tavily's answer, and no new AI provider is introduced.
   *
   * Backward compatible: omitting `lang` (or passing a value other than
   * "bn"/"en") sends exactly the same request as before this change.
   */
  async search(query, lang) {
    const apiKey = process.env.TAVILY_API_KEY;
    if (!apiKey) {
      console.warn("⚠️ [TAVILY] API Key missing. Skipping web search.");
      return null;
    }

    let outgoingQuery = query;
    if (lang === "bn") {
      outgoingQuery = `${query} (দয়া করে বাংলায় উত্তর দিন)`;
    } else if (lang === "en") {
      outgoingQuery = `${query} (please answer in English)`;
    }

    try {
      const response = await fetch("https://api.tavily.com/search", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          api_key: apiKey,
          query: outgoingQuery,
          search_depth: "basic",
          include_answer: true, // Tavily নিজে থেকেই একটি AI সামারি পাঠাবে
          max_results: 3,
        }),
      });

      if (!response.ok) return null;

      const data = await response.json();

      // যদি Tavily সরাসরি উত্তর তৈরি করে দেয়
      if (data.answer) return data.answer;

      // নাহলে সেরা ৩টি রেজাল্ট থেকে টেক্সট তুলে আনা
      if (data.results && data.results.length > 0) {
        return data.results.map((r) => r.content).join("\n\n");
      }

      return null;
    } catch (error) {
      console.error("[TAVILY] Request failed:", error.message);
      return null;
    }
  }
}

module.exports = new TavilySearch();
