sonar.projectKey=orbisaideveloper_orbis-foundation
sonar.organization=orbis
sonar.projectName=orbis-foundation
sonar.sources=src,orbis-server
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx,**/*.test.cjs
