export enum LifecycleState {
  UNREGISTERED = "UNREGISTERED",
  REGISTERED = "REGISTERED",
  INITIALIZING = "INITIALIZING",
  READY = "READY",
  DEGRADED = "DEGRADED",
  STOPPING = "STOPPING",
  STOPPED = "STOPPED",
  FAILED = "FAILED",
}
