import { Role } from '../../contracts/admin.contracts';

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_USERS: 'MANAGE_USERS',
  SYSTEM_RESTART: 'SYSTEM_RESTART',
  DEPLOY_RELEASE: 'DEPLOY_RELEASE',
} as const;

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  GUEST: [PERMISSIONS.VIEW_DASHBOARD],
  OPERATOR: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.DEPLOY_RELEASE],
  ADMIN: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.MANAGE_USERS, PERMISSIONS.DEPLOY_RELEASE],
  SYSTEM: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.MANAGE_USERS, PERMISSIONS.SYSTEM_RESTART, PERMISSIONS.DEPLOY_RELEASE],
};

export const checkPermission = (role: Role, permissionId: string): boolean => {
  return ROLE_PERMISSIONS[role]?.includes(permissionId) ?? false;
};
